Update dev script to echo when a command isn't found.

diff --git a/scripts/dev b/scripts/dev
--- a/scripts/dev
+++ b/scripts/dev
@@ -10,6 +10,9 @@ if [ $# -gt 0 ]; then
   elif [ "$1" == "test:watch" ]; then
     shift 1
     docker-compose run --rm server npm run test:watch "$@"
+  else
+    echo "dev: Command not found."
+    exit 1
   fi
 else
   docker-compose ps
